### ISSUE TITLE
请站长在今后版本中考虑Valine+gitment的搭配

### ISSUE THREAD

**Issue by CallMeSkyCN** [codefine/hexo-theme-mellow#10]
请站长在今后版本中考虑Valine+gitment的搭配（在配置文件或者文件头中选择具体使用哪个）

**Comment by codefine** [comment]
@CallMeSkyCN 下个迭代加入gitment

**Comment by codefine** [comment]
@CallMeSkyCN 
add gitment with [v1.2.6](https://github.com/codefine/hexo-theme-mellow/releases/tag/v1.2.6)
