### ISSUE TITLE
在分类文章较少的情况下，底部footer会跑起来，希望把它压下去

### ISSUE THREAD

**Issue by Twor** [codefine/hexo-theme-mellow#11]
![](http://oi9k0dp1f.bkt.clouddn.com/2017-12-26-233915_1366x768_scrot.png)

**Comment by codefine** [comment]
@Twor 收到，下个迭代更正

**Comment by codefine** [comment]
fixed this bug with [v1.2.6](https://github.com/codefine/hexo-theme-mellow/releases/tag/v1.2.6)
