### ISSUE TITLE
分类界面异常

### ISSUE THREAD

**Issue by pipigou** [codefine/hexo-theme-mellow#14]
按照wiki创建好categories界面后，直接点击分类界面，会出现下面的界面，而不会显示全部分类：
![1](https://user-images.githubusercontent.com/8373214/36404013-65f085ec-1623-11e8-8447-cd6f2d4607ac.jpg)
但点击博客主页卡片上的分类可以正常显示：
![2](https://user-images.githubusercontent.com/8373214/36404081-beacdcc6-1623-11e8-9524-ddfe54665d17.jpg)
![3](https://user-images.githubusercontent.com/8373214/36404102-d38e5a3e-1623-11e8-8a83-fbae7fc6d085.jpg)
点击全部后会回到第一幅图片的样子
这是有关 的一些设置：
![4](https://user-images.githubusercontent.com/8373214/36404136-0685ce36-1624-11e8-9a6b-4b9bf06cd054.jpg)
请问这是什么原因，谢谢！！！

**Comment by codefine** [comment]
@pipigou 不好意思，刚收假，才看到。你的问题可能是没创建分类页源文件或者是没修改对应的布局。

开启分类、标签页等，不仅需要在主题配置文件的`menu`中开启，还需要用命令行进行创建，具体方法：
先用`hexo new page categories`创建分类页源文件，然后在`source/categories/index.md`中修改`layout: categories`。

这样应该就ok了。在wiki菜单栏目的底部有说明[菜单](https://github.com/codefine/hexo-theme-mellow/wiki/2.-%E4%B8%BB%E9%A2%98%E5%B8%B8%E8%A7%84%E9%85%8D%E7%BD%AE#%E8%8F%9C%E5%8D%95)
