### ISSUE TITLE
关于分享失败的问题

### ISSUE THREAD

**Issue by formattedzzz** [codefine/hexo-theme-mellow#2]
**微博**：ok
**微信**：扫码之后提示什么什么非微信官方网页，点击继续访问无响应
**qq**：移动端qq内置浏览器ok，PC端有提示信息，如下：
![](http://owdef1yjt.bkt.clouddn.com/blogbug.png)

**Comment by codefine** [comment]
@formattedzzz 感谢测试，已收到。最近比较忙，我测试好了后回复你。抱歉。

**Comment by codefine** [comment]
@formattedzzz 不好意思，终于闲下来了，能测试一下了。
经过测试发现，微信现在的策略是所有页面都会经过一个预处理，屏蔽所有点击事件以及一些其他事件，这导致原网页功能几乎全部失效。解决方法得通过公众号配置才行，比较麻烦，暂时没啥好办法。
QQ分享的问题我没有发现，可以把具体的链接发给我测试一下。
