### ISSUE TITLE
代码行bug了，变成一行了

### ISSUE THREAD

**Issue by YuanLiChenAi** [codefine/hexo-theme-mellow#20]
hexo生成后第一部分代码变成一行，行号也挤在一起了变成123，后面的代码没有变化
![14a180ec571d8111f63937f26bd09ef8](https://user-images.githubusercontent.com/37205011/37651399-f473e56a-2c72-11e8-8b4a-d4bb83264579.png)
这是md文件里面的
![bca7ec368ffdc33963d325ef8ea6b2bf](https://user-images.githubusercontent.com/37205011/37651404-fd676606-2c72-11e8-8b38-86fb74651089.png)

**Comment by codefine** [comment]
已修复
