### ISSUE TITLE
插入代码后显示效果出现异常

### ISSUE THREAD

**Issue by saltpi** [codefine/hexo-theme-mellow#21]
在md源文件中插入代码：
```C++
typedef struct{
	ElemType *elem;      //结构体的基地址
	int length;          //顺序表中实际存放的元素个数
	int listsize;        //顺序表中能够存放的元素个数
}Sqlist;//结构体名
```
![](http://ozkg680jm.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-04-03%20%E4%B8%8B%E5%8D%889.14.25.png)
显示效果：

![](http://ozkg680jm.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-04-03%20%E4%B8%8B%E5%8D%889.14.42.png)
经测试如果在代码块前面插入一个任意代码，第二个代码显示正常
![](http://ozkg680jm.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-04-03%20%E4%B8%8B%E5%8D%889.21.44.png)

效果：
![](http://ozkg680jm.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-04-03%20%E4%B8%8B%E5%8D%889.22.15.png)
希望老哥尽快解决@-@

**Comment by ourfor** [comment]
![](http://ozkg680jm.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-04-03%20%E4%B8%8B%E5%8D%889.14.42.png)

**Comment by saltpi** [comment]
显示效果：http://ozkg680jm.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-04-03%20%E4%B8%8B%E5%8D%889.14.42.png

**Comment by saltpi** [comment]
显示为单行，并且莫名其妙多的几个数字

**Comment by codefine** [comment]
之前有人提出过这个单行问题，我已经修复并更新了主题包，请更新最新的主题

**Comment by saltpi** [comment]
更新了好像依旧存在

**Comment by codefine** [comment]
@ourfor 已修复，请更新主题包

**Comment by codefine** [comment]
此次修改会影响到页面的`<table>`标签。
为了兼容原有的表格，需要加入table的class标识符，即：
`<table>` -> `<table class="table">`

**Comment by saltpi** [comment]
多谢
