### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by saltpi** [codefine/hexo-theme-mellow#24]
目前这款主题很强大也很简洁，但窝觉得还是有些地方可以改进一下：
- 点击图片可以进行缩放(比如，Next主题那样)
- 是否考虑加一些音乐的控件，可以全局播放啥的(比如,咚门的WordPress主题[Always](http://www.dearzd.com/DBlog/)那种类型的` Playlist `)

也不知道我的建议是否有违作者的初心或者理念，若有请忽略！😂

**Comment by codefine** [comment]
* 图片缩放考虑加入
* 全局音乐控件过于客制化，暂不考虑
---
关闭这个issue的时候会更新以上需要完善功能

**Comment by codefine** [comment]
@ourfor

加入图片灯箱功能[v1.3.3](https://github.com/codefine/hexo-theme-mellow/releases/tag/v1.3.3)
