### ISSUE TITLE
可否加入首页摘要渲染开关？

### ISSUE THREAD

**Issue by miranquil** [codefine/hexo-theme-mellow#25]
RT，现在首页文章的摘要都是未经渲染的原文本，看起来并不美观。摘要很多时候也可以用富文本写巧的，这里能给加个配置文件开关就很完美了。

我现在用的是Next主题，正在考虑更换Mellow，唯一阻拦就是这个qwq。

**Comment by codefine** [comment]
@yorushika

来个预览地址，我瞅瞅先

**Comment by miranquil** [comment]
https://sh.alynx.xyz/
