### ISSUE TITLE
大佬

### ISSUE THREAD

**Issue by ghost** [codefine/hexo-theme-mellow#26]
# 建议加入一个代码高亮就像NexT这样的代码高亮很不错

**Comment by codefine** [comment]
@cyueo 

本主题中已经有代码高亮功能，[演示地址](http://blog.lujingtao.com/2017/11/19/hexo-deploy/#%E9%80%9A%E8%BF%87git%E5%AE%8C%E6%88%90%E9%83%A8%E7%BD%B2)。

一般代码段采用` ``` 代码语言 `的形式开头并且以` ``` `结尾，请使用这种[标准的markdown语法](https://segmentfault.com/markdown#articleHeader1)即可实现代码高亮。

---

如有理解偏差，请补充详细说明。
