### ISSUE TITLE
img标签引用图片，在图片上方会多一个'>'

### ISSUE THREAD

**Issue by saltpi** [codefine/hexo-theme-mellow#31]
如下图，img标签引用图片会出现，而使用MarkDown的方式则没有这种情况
![2018-09-29 12 51 04](https://user-images.githubusercontent.com/33711476/46241176-cfbd8a80-c3e6-11e8-92ee-f4314487fe28.png)

**Comment by saltpi** [comment]
- 移动端点击查看图片，无法放大，通过上划关闭图片，有考虑移动端也加按钮来关闭当前图片吗？

**Comment by codefine** [comment]
@ourfor 

* 用img标签上方多处一个>，我测试了一下，无法复现，__提供一下markdown源文件__
* 这个图片灯箱是我找的一个叫swipebox的插件，当时对比了很多类似的，就这个还行。你说的这个也是问题，__我再找找__

**Comment by saltpi** [comment]
- [样例](https://github.com/ourfor/Show_picture)
- [markdown源文件](https://github.com/codefine/hexo-theme-mellow/files/2460612/Android_Beta_Software.md.zip)

**Comment by codefine** [comment]
* 图片上方多一个>的问题已经修复
* 提供的灯箱例子引入了过多其他依赖，再考虑一下

**Comment by saltpi** [comment]
https://github.com/codefine/hexo-theme-mellow/blob/b27f79454031a141a713c34ffb014cb1f569e47b/layout/_partial/script.ejs#L11

```
<!--fancybox-->
<script src="//code.jquery.com/jquery-3.3.1.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.2/dist/jquery.fancybox.min.css" />
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.2/dist/jquery.fancybox.min.js"></script>
```

https://github.com/codefine/hexo-theme-mellow/blob/b27f79454031a141a713c34ffb014cb1f569e47b/layout/_partial/post.ejs#L25
```
return `<a rel=${post.title} href="${src}"  title="${title}" data-fancybox="images">${img}</a>`
```

[fancybox](http://fancyapps.com/fancybox/3/)
