### ISSUE TITLE
gitment 的驗證失效 

### ISSUE THREAD

**Issue by dandanXO** [codefine/hexo-theme-mellow#34]
估計是原作者域名驗證失效了
[這裡](https://github.com/imsun/gitment/issues/170)
[有解決方案](https://xiaotiandi.github.io/publicBlog/2018-09-19-d196c9ad.html)
是否請作者提供修改方案或是gitment 插建 原始碼位置

**Comment by codefine** [comment]
@dandanXO 

已经解决好了，下午我更新主题仓库之后关闭这个issue，你晚一些更新。
