### ISSUE TITLE
图片放在表格里面，href会变成undefine，无法点击查看查看

### ISSUE THREAD

**Issue by saltpi** [codefine/hexo-theme-mellow#36]

**Comment by saltpi** [comment]
如图:
<img width="640" alt="2018-12-19 9 12 10" src="https://user-images.githubusercontent.com/33711476/50222298-d26ec100-03d2-11e9-9ace-06890451f613.png">
Markdown源文件[查看](https://file.ourfor.top/source/other/MI6_Optimization.md)

**Comment by saltpi** [comment]
- 之前也有发现以img方式引用图片也会有这种情况。

**Comment by ourfor** [comment]
- 之前也有发现以<img>方式引用图片也会有这种情况。

**Comment by codefine** [comment]
@ourfor 

问题已经找到了，我解析图片src的正则写的有点问题。

下午改好更新仓库。

**Comment by saltpi** [comment]
OK，感谢👏

**Comment by codefine** [comment]
@ourfor 

主题仓库已经更新了。

另外，markdown里的图片外面不需要自己套a标签，主题会给所有的img包一层fancybox需要用的a标签
