### ISSUE TITLE
关于进入文章页后如何自动关闭左侧菜单栏

### ISSUE THREAD

**Issue by gaoqiang1991a** [codefine/hexo-theme-mellow#39]
目前进入文章详情页后左侧的菜单栏会自动显示，能否像indigo主题那样通过可配置项实现文章详情页菜单栏的自动关闭？谢谢！

**Comment by codefine** [comment]
@gaoqiang1991a 可以的

可以的，最近出了点事故，回复晚了。抱歉了，等我更新主题。

**Comment by gaoqiang1991a** [comment]
好的，辛苦大佬了，目前正在使用这个主题，挺好用的

**Comment by codefine** [comment]
感谢支持，最迟明天更新

**Comment by codefine** [comment]
@gaoqiang1991a https://github.com/codefine/hexo-theme-mellow/releases/tag/v1.4.2
