### ISSUE TITLE
可以展示自己的项目

### ISSUE THREAD

**Issue by cvenwu** [codefine/hexo-theme-mellow#4]
自己有一个idea，有的hexo博客可以展示自己的GitHub上做的项目，例如[“演示”](http://dongchuan.github.io/)这个主题的博客上面可以展示自己的开源项目，甚至还可以展示地点！

**Comment by codefine** [comment]
@sivanWu0222 

经过一番考察，发现这个需求很容易就能实现，主要是用到这个API：
``` html
https://api.github.com/users/${username}/repos
```
会返回一个 `username` 下的所有开源仓库的所有信息的一维数组。循环生成DOM结构就可以了。

只是这个需求我暂时没找到一个不破坏整体博客风格的，合适的地方放置。有什么建议么？

另外你说的 **甚至可以展示地点**，地点是什么意思，这个我没看明白。

**Comment by cvenwu** [comment]
地点的话是自己在配置文件中进行配置，因为自己想了一下如果不做到破坏博客风格的话，可能就要像next主题那样多配制几个不同的分支，一个是有侧，一个是头部导航栏(展示自己的项目使用)
