### ISSUE TITLE
图片路径，markdown和网页显示不一致

### ISSUE THREAD

**Issue by LiuFG** [codefine/hexo-theme-mellow#49]
`<img src="./文章名/graph.PNG" alt="graph"  />`可以在本地markdown内显示，但是部署到网页上后，无法显示图片。只有改成`<img src="graph.PNG" alt="graph"  />`网页才能显示，但是此时markdown本地无法显示图片

**Comment by YuanLiChenAi** [comment]
主文件配置以及图片文件保存位置

**Comment by LiuFG** [comment]
> 主文件配置以及图片文件保存位置
主文件配置了post_asset_folder: true，图片保存在了自动生成的文件夹下。这样会出现上述问题，请问还需要配置什么么？

**Comment by YuanLiChenAi** [comment]
https://github.com/codefine/hexo-theme-mellow/wiki/7.-%E5%9B%BE%E7%89%87%E5%BC%95%E7%94%A8#%E5%BC%95%E5%85%A5%E7%A4%BA%E4%BE%8B
