### ISSUE TITLE
文章进去之后，怎么能不显示主页的缩略图

### ISSUE THREAD

**Issue by runzhenghengbin** [codefine/hexo-theme-mellow#7]
- 文章详情页面不想显示 设置的缩略图，怎么设置？
- 文章详情页面的 目录怎么设置的？看博主的有？
我的地址：https://runzhenghengbin.github.io/

**Comment by codefine** [comment]
@runzhenghengbin

目录重做了，之前那个有点问题。

缩略图在mellow/_config.yml，搜索关键字thumb，设置为false就好。

不过可以稍等一下，我回去修改一些样式问题再更新一下仓库，你可以先看看仓库的wiki，等这个没问题的新版本再使用。

**Comment by codefine** [comment]
@runzhenghengbin 主题仓库已经更新了，请下载使用。
