### ISSUE TITLE
我也用这个主题

### ISSUE THREAD

**Issue by runzhenghengbin** [codefine/hexo-theme-mellow#8]
[养码青年](https://runzhenghengbin.github.io/)

**Comment by codefine** [comment]
@runzhenghengbin 已添加，感谢使用。

**Comment by codefine** [comment]
@runzhenghengbin 关于右上角的播放器功能，给你提一个改善体验的方案，可以尝试一下。

加入缓存，页面跳转不重置播放。

思路：使用hexo的辅助函数 `partial` 与 `fragment_cache` 组合，有望实现。

[https://hexo.io/zh-cn/docs/helpers.html#partial](https://hexo.io/zh-cn/docs/helpers.html#partial)
