### ISSUE TITLE
新版是出于什么考虑把正文区域宽度缩小呢?

### ISSUE THREAD

**Issue by magicpose** [codefine/hexo-theme-mellow#9]
感觉原来的宽度很舒服,使用makedown写代码块,比较长的代码,原来正好能显示全,现在都要拉滚动条才能看见...
```
"Attach Listener" #12 daemon prio=9 os_prio=31 tid=0x00007ff0f780c800 nid=0x4507 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
```

**Comment by magicpose** [comment]
看来是要通过"variable.less"去自定义一套了

**Comment by codefine** [comment]
@magicpose 主要是原来的那个宽度不太适合缩略图的显示。然后我也考虑到不使用缩略图的情况，所以我在`variable.less`中把这个首页宽度和文章宽度的设置都放出来了，可以随意调节，跟着感觉走。😄

**Comment by formattedzzz** [comment]
对了老哥，新版的自适应漏了iPadmini那段区间，我参考你那段区间的margin时发现的，下次加上就好了

**Comment by codefine** [comment]
@formattedzzz 👌

**Comment by magicpose** [comment]
@codefine 嗯,看到能自定义就好了,挺灵活的.主题不错

**Comment by codefine** [comment]
@magicpose 感谢使用，主题还很年轻，你的issue是我更新的动力。哈哈哈。
